RIGHT         seek 5
l             seek 5
LEFT          seek -5
j             seek -5
MBTN_LEFT     cycle pause
SPACE         cycle pause
k             cycle pause
MBTN_LEFT_DBL cycle fullscreen
f             cycle fullscreen
MBTN_RIGHT    cycle mute
m             cycle mute
ESC           quit
WHEEL_UP      add volume 1
UP            add volume 5
WHEEL_DOWN    add volume -1
DOWN          add volume -5