################
### KEYWORDS ###
################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set keyword aliases to things that you use:
$prefix = exec-app
$terminal = konsole
$fileManager = dolphin
$menu = dms ipc call spotlight toggle
$clipboard = kitty --class clipse -e clipse
$emoji = plasma-emojier
$screenshotUtil = hyprctl keyword cursor:use_cpu_buffer true && hyprshot -m region -s -z --clipboard-only && hyprctl keyword cursor:use_cpu_buffer false
$screenshotUtilEdit = hyprctl keyword cursor:use_cpu_buffer true && hyprshot -m region -s -z -o '/tmp' -- gwenview && hyprctl keyword cursor:use_cpu_buffer false
$keybindMenu = dms ipc call keybinds toggle hyprland
