###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly for security reasons.

# As of 0.54 these are broken ATM so turning them off.

ecosystem {
   enforce_permissions = 0
}

permission = /usr/bin/grim, screencopy, allow
permission = /usr/bin/dms, screencopy, allow
permission = /usr/bin/quickshell, screencopy, allow
permission = /usr/bin/hyprpicker, screencopy, allow
permission = /usr/lib/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/hyprpm, plugin, allow
